#spring:
#  application:
#    name: coreDB
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: Harshil84012
#    url: jdbc:mysql://proddb.cx66mowuwav5.us-east-1.rds.amazonaws.com:3306/prodDB?createDatabaseIfNotExist=true
#    username: admin
#  jpa:
#    hibernate:
#      ddl-auto: update