spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/harshil
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 9090

jwt:
  auth:
    converter:
      resource-id: harshil-rest-api
      principle-attribute: harshil
